import Head from "next/head";
import SideNavbar from "../components/SideNavbar";
import Main from "../components/Main";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Responsive Side-Navbar</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/pro.ico" />
      </Head>
      <SideNavbar />
      {/* <Main></Main> */}
    </div>
  );
}
